### ISSUE TITLE
Feature Request: Toggle to enable or disable plugin.

### ISSUE THREAD

**Issue by ItzBlue72** [Saxavlax001/PECollide#6]
#### Description
The plugin is great for messing around with other players, but the collisions often can get annoying in small spaces and can also be used to intentionally distract or disrupt other players. It would be cool if you could toggle this feature with a command so that the plugin can be disabled and enabled without having to restart the server to remove/install the plugin.

**Comment by Saxavlax001** [comment]
Hey,I obviously saw your message and ignored it for a long time,because I didn't have the time or creativity those days to make this possible, but I want to mention that I just finished your request with success by using a default config.yml file and a very simple command for both in game and console to enable/disable it. I'll upload changes right now and I hope poggit reviewers will accept my changes to release it.
